print('olá, mundo!')
print('Bom dia!')
print('Como está?')
print('caramba')
print('ouvir funk pela manhã é muito bom')
print('Bolo de cenoura com chocolate dlç')
print('Estou com sono')
print('Sextouuuuu')
print('Programando ;-)')
print('Programadora agora, silêncio estou programando')
